plugin_repo(
  name = "python",
  revision = "wheel_resolver-v2.0.0",
  plugin = "python-rules",
  owner = "please-build",
)
plugin_repo(
  name = "go",
  revision = "v1.26.0",
  plugin = "go-rules",
  owner = "please-build",
)
